server/actions/User.ts, server/models/Attribute.ts, server/models/Category.ts, server/models/InventoryItem.ts, server/models/ItemDefinition.ts, server/models/User.ts, utils/types/api.ts, utils/types/index.ts, utils/types/models.ts
This PR adds the schema definitions for mongoose/MongoDB into the `server/models` folder. They match up with the description from [CCAHT-11](https://team-16679321250140.atlassian.net/browse/CCAHT-11) exactly.
In the `utils/types` folder I created three files:
-  `models.ts` contains our model types and are used in the mongoose schema definitions to export the `[Entity]Document` interface.
- `api.ts` defines an `ApiError` class which will be useful for error handling, along with an interface for an `ApiResponse` which will be returned on all API requests.
- `index.ts` exports everything from the other two files, allowing the types to be imported using the following syntax:
```js
import { [type] } from '@/utils/types'
```
(The '@' symbol just means the root of the project, when actually …
=> CCAHT-11 setup types and mongoose schema

components/HeaderAppBar/index.tsx, pages/_app.tsx
Resolves [CCAHT-48](https://team-16679321250140.atlassian.net/browse/CCAHT-48)
The `<AppBar>` component was previously overlapping with the content of the page. This PR:
- Fixed the display issues, the page content is now rendered slightly below the `<AppBar>` component
- Hooked up the Navigation Drawer and AppBar components via a `useState` in their parent (`_app.tsx`)
Below is what the page looks like currently
Here is what it looks like with the implemented changes
[CCAHT-48]: https://team-16679321250140.atlassian.net/browse/CCAHT-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed display issues

components/CheckInOutForm/QuantityForm.tsx, components/CheckInOutForm/index.tsx, components/DefaultLayout/index.tsx, components/NavigationDrawer/index.tsx, pages/_app.tsx, pages/api/attributes/[attributeId].ts, pages/api/attributes/index.ts, pages/api/categories/[categoryId].ts, pages/api/categories/index.ts, pages/api/itemDefinitions/[itemDefinitionId].ts, pages/api/itemDefinitions/index.ts, pages/api/users/[userId].ts, pages/api/users/index.ts, server/actions/ItemDefinition.ts, server/actions/MongoDriver.ts, server/models/Attribute.ts, server/models/Category.ts, server/models/InventoryItem.ts, server/models/ItemDefinition.ts, server/models/User.ts, tsconfig.json, utils/apiValidators.ts, utils/auth.ts, utils/theme.ts, utils/types/index.ts
Edited tsconfig.json to support absolute paths and aliases. In some small cases, the paths got longer, however the majority of the paths got shorter and are easier to read.
A few notes:
- Use the alias `@api/` to access anything from `./pages/api/`
- When using the `Image` component from `next/image`, start the `src` path with a `/` and assume that you are already in `public/`
For example, with relative paths, the CCAHT logo would be: `/public/images/CCAHT-Logo.png`.\
Using absolute paths, that would be: `/images/CCAHT-Logo.png`. If you attempt to include `public/` you will get an error.
**Any open PR's and future changes after this PR is merged should use absolute paths.**
Also if there are any paths that are being used repetitively, we should consider making them an alias.
=> CCAHT-78-Switch-imports-to-use-absolute-paths

package-lock.json, package.json
Here's how I tested this out in the screenshot above. There were typescript related issues with the link given in the story, so Andrew and I found a package that will cover the debounce characteristic. Be sure to run `npm install` to get the new package.
=> debounce package

components/CheckInOutForm/index.tsx, pages/checkIn.tsx, pages/checkOut.tsx
- Added a category dropdown option in the `CheckInOutForm` component using the item dropdown for reference.
- Added a `categories` prop.
- Used `useState` to store the category selected, using the item `useState` as reference.
- Added `categories` to check in and check out pages.
~~*Draft pull request until CCAHT-24 is merged, so I can add the `categories` prop to it.*~~
=> CCAHT-38-Add-category-dropdown-to-check-in-check-out-form-component

components/AttributeAutocomplete/index.tsx, components/CheckInOutForm/index.tsx, pages/checkIn.tsx, pages/checkOut.tsx, utils/attribute.ts, utils/types/models.ts
- created some utility types in `utils/models.ts`
- `OptionsAttribute`, `TextAttribute`, and `NumberAttribute` -- these types hold a specific type or value for their `possibleValues` field, useful when wanting to only accept a certain kind of attribute
- `AttributePossibleValues` -- union type containing the types that a regular `Attribute`'s `possibleValues` field can hold
- `AttributeRequest` -- the data that will be sent to the server when requesting an Attribute. This may need to be revisited.
- created utility functions and types in `utils/attribute.ts`
- `SeparatedAttributes` -- defines a type that contains each kind of attribute, keyed on the kind of attribute it is
- `separateAttributes` -- splits the attributes by type and returns a `SeparatedAttributes` object
- created …
=> CCAHT-39 Attributes!

components/AttributeAutocomplete/index.tsx, components/CheckInOutForm/index.tsx, pages/checkIn.tsx, pages/checkOut.tsx
I implemented the filtering based on the category for item definitions. I also noticed I implemented the attributes field wrong, so I fixed that to use the selected item definitions attributes.
Here is the data I used to test:
```ts
const testCategories: Category[] = [
{
_id: '1',
name: 'testCategory',
},
{
_id: '2',
name: 'testCategory2',
},
]
const testItemDefinitions: ItemDefinition[] = [
{
_id: '1',
name: 'testItemDefinition',
category: testCategories[0],
internal: true,
lowStockThreshold: 10,
criticalStockThreshold: 5,
attributes: [
{
_id: '1',
name: 'testAttribute',
possibleValues: ['test1', 'test2'],
color: '#FF0000',
},
{
_id: '2',
name: 'test2',
possibleValues: 'number',
color: '#00FF00',
},
],
},
{
_id: '2',
name: 'testItemDefinition2',
category: testCategories[1],
internal: …
```
=> CCAHT-90 add category and attribute filtering

utils/dbTestData.script
Clears out and then populates the database with LOTS of test data. If you don't want to clear out the database, and only add to it, set the conditional on line 4 to false.
Edge cases I considered:
- ItemDefinitions without a category (ID 27 & 28)
- Category without ItemDefinitions (ID 8)
- ItemDefinitions without attributes (several)
- InventoryItems without all possible attributes (Several, all in categoryId 1 I believe). 
- 0 quantity
- low/critically low quantity
- internal items with assignees on the inventoryItem
- Different color attributes
If there are any more considerations, let me know.
You don't have to pour over every line, but at least visit every section and make sure that the format/objects are correct. I've ran this, so it's all in the database and works, but none of it …
=> Ccaht 80 create mongo db test data setup script

pages/api/attributes/[attributeId].ts, pages/api/attributes/index.ts, pages/api/categories/[categoryId].ts, pages/api/categories/index.ts, pages/api/inventoryItems/[inventoryItemId].ts, pages/api/inventoryItems/index.tsx, pages/api/itemDefinitions/[itemDefinitionId].ts, pages/api/itemDefinitions/index.ts, pages/api/users/[userId].ts, pages/api/users/index.ts, pages/inventory.tsx, server/actions/InventoryItems.ts, server/actions/ItemDefinition.ts, server/actions/MongoDriver.ts, test/api/attributes/[attributeId].test.ts, test/api/attributes/index.test.ts, test/api/categories/[categoryId].test.ts, test/api/categories/index.test.ts, test/api/inventoryItems/[inventoryItemId].test.ts, test/api/inventoryItems/index.test.ts, test/api/itemDefinitions/[itemDefinitionId].test.ts, test/api/itemDefinitions/index.test.ts, test/api/users/[userId].test.ts, test/api/users/index.test.ts, test/server/MongoDriver.test.ts, test/testData.ts, utils/types/requests.ts, utils/validators.ts
This PR fulfills [CCAHT-56](https://team-16679321250140.atlassian.net/jira/software/projects/CCAHT/boards/1?selectedIssue=CCAHT-56), putting the InventoryItemList component on the Inventory page.
In the process, I also make the CRUD api endpoints/server funcs for inventoryItems. Added a few TODOs for some tech-debt to cover in the future.
Also renamed API handlers to be more descriptive, since we'll be calling them directly in the future.
In writing the tests, I created `testData.ts`, which hosts all of our test data so we don't have hard-coded constants
[CCAHT-56]: https://team-16679321250140.atlassian.net/browse/CCAHT-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ccaht 56 hook up inventory page and inventory item list component 2

pages/settings/items.tsx
Tiny story, adds:
- a "Items" header
- a search box
- a "Create New Item" button
To test, just go to `settings/items` page.
There is no deliberate mobile support since the table only works well on desktop, however, the setup is somewhat responsive. If we add a mobile version of the table later, this might need to be changed. **Note:** the table is not in this PR.
=> CCAHT-126-Populate-Items-Settings-page

pages/settings/items.tsx
Hooked up Items Settings page with database to populate the table.
Hooked up search query to table, now supports searching by name, category, attribute, and consumer.
Note: The create new item button functionality will be dealt with in another PR.
To test, just go to `settings/items` page.
**DO NOT** merge until [CCAHT-125](https://team-16679321250140.atlassian.net/browse/CCAHT-125) / #81  and [CCAHT-126](https://team-16679321250140.atlassian.net/browse/CCAHT-126) / #83  are merged in!
As with [CCAHT-126](https://team-16679321250140.atlassian.net/browse/CCAHT-126) / #83: There is no deliberate mobile support since the table only works well on desktop, however, the setup is somewhat responsive. If we add a mobile version of the table later, this might need to be changed.
[CCAHT-125]: …
=> CCAHT-127-Put-ItemDefinitionList-component-onto-Items-Settings-page-and-hook-up-to-backend

.eslintrc.json, components/DefaultLayout/index.tsx, components/InventoryItemListItemKebab/index.tsx, pages/checkIn.tsx, pages/checkOut.tsx, pages/index.tsx, store/index.ts, store/snackbar.ts, store/types.ts
Added in a snackbar service using Redux to make it easy to display a snackbar. Check out examples in `pages/checkIn.tsx` `pages/checkOut.tsx` and `components/InventoryItemListKebab/index.tsx`
When this gets merged, remind me to update documentation for using this service.
=> CCAHT-105 add snackbar service and update existing calls to use it

components/HistoryList/DesktopHistoryList/index.tsx, components/HistoryList/MobileHistoryList/index.tsx, pages/history.tsx
Now, when clicking the "Export to Excel" button on the history page, it downloads a csv with the currently visible logs, taking into account any filters, and always sorting by date.
To do this I had to pull the state of each list out into the page, which is a cleaner pattern anyways.
Give it a try on your machine and make sure you can easily open up the downloaded file in a spreadsheet, and also review the format of the spreadsheet.
=> Ccaht 161 add functionality to export to excel button

pages/settings/items.tsx, utils/transformations.ts
Hooks up `Create New Item` button to the new item dialog in `items/new` using the `DialogLink` component.
A extra item query param appears after an item is created, this is for the check in page and is not used here.
To test, go to `settings/items` page.
**DO NOT** merge until [CCAHT-127](https://team-16679321250140.atlassian.net/browse/CCAHT-127) / #84 and [CCAHT-62](https://team-16679321250140.atlassian.net/browse/CCAHT-62) / #76 are merged in!
This branch only changes `settings/items.tsx` the other changes are apart of CCAHT-62.
[CCAHT-127]: https://team-16679321250140.atlassian.net/browse/CCAHT-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCAHT-62]: https://team-16679321250140.atlassian.net/browse/CCAHT-62?atlOrigin=eyJpIjoiNWRkNTljN …
=> Ccaht 128 hook up create new item button to create new item form dialog

server/models/Attribute.ts, server/models/Category.ts, server/models/InventoryItem.ts, server/models/ItemDefinition.ts, server/models/Log.ts, server/models/NotificationEmail.ts, server/models/User.ts
Here's the explanation. Fix was to disable document versioning.
Prettier made it look like a lot more changes than it actually is. The only change is adding this to all schema definitions
```
{
versionKey: false,
}
```
=> CCAHT-169 removed document versioning from schemas

pages/api/attributes/[attributeId].ts, pages/settings/attributes/[attributeId]/edit.tsx, pages/settings/attributes/create.tsx, pages/settings/attributes/index.tsx, utils/constants/dialogRoutes.ts
Can now add attributes on settings page
Misc. stuff:
- added loading button on create new attribute button and edit attribute kebab option
- Can't create an attribute with no name (which threw you into an infinite loading button)
Not covered
- Something to tell the user that their attribute with no name didn't get made (how should I go about this, a snackbar?)
=> Ccaht 136 hook up upsert attribute form to create new attribute button

components/CategoryList/index.tsx
previously, 'admin' would be sorted after 'Clothing' because the sort was case sensitive
=> Sort category table by lowercase string

components/AttributeAutocomplete/index.tsx, components/CheckInOutForm/index.tsx, components/SearchAutocomplete/index.tsx, components/UpsertAttributeForm/index.tsx, components/UpsertItemForm/index.tsx
Self explanatory, after clicking a dropdown, the first item in the list is auto-highlighted and select-able.
=> CCAHT-150 Add auto highlight to all AutoCompletes

pages/checkIn.tsx
Per Jira:
If you click on Create New Item on the check in page and then click the “Cancel”  button, the query will contain `item=undefined`
This PR fixes this issue.
=> fix undefined item query on check in page

components/AttributeList/index.tsx, pages/settings/attributes/[attributeId]/edit.tsx, pages/settings/attributes/create.tsx
This makes the table sorting case insensitive
However, I noticed a lot more issues on the attributes page
1. The search wasn't taking into account lowercase names for some reason (FIXED)
2. The create button sent you to the api endpoint instead of the settings page when you hit submit (FIXED)
3. Creating an attribute does not make it appear on the page right away (it used to a while ago, idk what changed) (NOT FIXED)
4. Editing an attribute is now broken because zod thinks the objectId isn't valid (?) (NOT FIXED)
=> CCAHT 194 make item attribute page sorting case-insensitive

components/ItemDefinitionList/DesktopItemDefinitionList/DesktopItemDefinitionListItem/index.tsx, components/ItemDefinitionList/DesktopItemDefinitionList/index.tsx
Also changed the "Low stock/critically low stock" table header to dispaly on one line instead of two -- on two lines the header is larger than all of the other pages. Revert the second commit if you disagree
=> Ccaht 236 item definition table row is taller than the other settings pages rows

components/AttributeList/AttributeListItem/index.tsx, components/AttributeList/index.tsx, components/CategoryList/index.tsx, components/ItemDefinitionList/DesktopItemDefinitionList/index.tsx, pages/settings/attributes/index.tsx, pages/settings/categories/index.tsx, pages/settings/items/index.tsx
- CCAHT-243 only pertains to `components/AttributeList/AttributeListItem/index.tsx`
- `my: 0.5` is there for mobile view. It's probable you can make a reusable function when working on the mobile view
Forgot to switch branches when completing [CCAHT-232](https://team-16679321250140.atlassian.net/browse/CCAHT-232). Third and fourth commits on this PR are for that story, and that PR description is as follows:
- I updated the default pagination on the settings pages to 10 so that the appearance of a scrollbar isn't jarring when switching between settings and backend-paginated tables. Feel free to revert if you disagree.
- It didn't make sense to do this one and NOT [CCAHT-235](https://team-16679321250140.atlassian.net/browse/CCAHT-235), so please move both CCAHT-235 and CCAHT-232 to done if …
=> CCAHT-243 coloring and spacing on attribute list items

components/SearchField/index.tsx
So that holding down backspace doesn't trigger another database call before the backspace key starts repeating. Default character repeat delay on windows and iphone is 500, and 300 on android. Setting it at 501 didn't quite work, so up to 550 it is. 
The only change I made is the debounce delay, all other changes in the file are from prettier.
=> CCAHT-271 increased debounce time to 550

server/actions/InventoryItems.ts
Previously if there was a space in a field it would break the url and make it not clickable
=> CCAHT-276 fix spaces in critically low stock email url

pages/checkIn.tsx, pages/checkOut.tsx
God knows how I found this bug. Test by commenting out the fix and observing that you cannot check in/out shaving cream or vacuum cleaners (but for some reason you can with body wash? but it used to not work) if you navigate to checkin/out from a kebab, then, uncomment the solution and observe you can check in/out that item now.
Issue was that `"assignee": null` was sometimes getting encoded in the url. I don't know why it only happens sometimes.
=> CCAHT-227 Fix Zod validation fail on checkin/out from prefilled form with item name with more than one word

pages/api/itemDefinitions/present.ts, server/actions/ItemDefinition.ts
THIS WAS NOT TESTED. there's something up with my local repo that I was not able to figure out. Test by hitting the `GET api/itemDefintions/present` endpoint (which I did not know existed!) and verify that there are no internal items
=> Checkout Query do not display internal items

pages/api/auth/[...nextauth].ts
Seems obvious in hindsight, we were returning true if they were a disallowed email :)
Also removed the `|| ''` fallback value in the `.includes`. Don't think it's a present issue, but if a env file happens to have `,,` in it and someone somehow logs in with a google profile without an email, it would let them through. No errors are thrown if `.includes` gets null or undefined, so this just adds a little more confidence.
Tested by:
- Attempting to sign in with any email
- Attempting to sign in with an email on the ALLOWED_EMAILS env property (nice touch whoever put that in!)
- Changing '@ccaht.org' to '@vols.utk.edu' and verifying that I could log in with my school email but not others
=> Auth email domain restriction

.github/workflows/lint.yaml, components/InventoryItemList/InventoryItemContext.tsx, components/InventoryItemList/InventoryItemListItemKebab/index.tsx, components/InventoryItemList/index.tsx, package.json, pages/inventory.tsx
Simple. Added a context to allow the kebab component to access a `refetch` method without prop drilling. To test, go in to inventory and delete an item. skeleton loaders should appear to show that the app is refetching the data, and no full page reload should occur
ALSO:
fix workflow file for linting for better naming
bump version
=> add no refresh delete to inventory
