components/NavigationDrawer/NavigationDrawerListItem/index.tsx
components/NavigationDrawer/index.tsx
pages/_app.tsx

There was also some weirdness about the folder structure in the components so I updated that.
Using the Next Link component like the JIRA suggested.
W

CCAHT-9-set-up-routing

---

components/HeaderAppBar/index.tsx

As stated in the title. Using the MUI Avatar component to render the users avatar

CCAHT-19-Put-user-avatar-in-the-app-bar

---

server/actions/User.ts

Created the following functions in `server/actions/User.ts`:
- `getUser(id: number)`
- `updateUser(id: number, user: User)`
- `deleteUser(id: number)`
`createUser(user: User)` was already created from an earlier PR.

CCAHT-40 create server funcs for getting, updating and deleting users

---

pages/api/auth/[...nextauth].ts
pages/api/users/[userId]/index.ts
pages/api/users/index.ts
utils/auth.ts

Creates the following endpoints:
- `api/users` - POST, creates a user
- `api/users/[userId]` - GET, gets user with id
- `api/users/[userId]` - PUT, updates user with id
- `api/users/[userId]` - DELETE, deletes user with id
Also creates a helper in `utils/auth.ts` which authenticates and authorizes a user for an API request

CCAHT-41 user api endpoints

---

server/actions/Category.ts

This PR adds CRUD server functions for Categories
The functions created are 
getCategories() - returns all categories from the database
getCategory(id: string) - returns the category with the given id from the database
updateCategory(id: string, category: Category) - updates the category with the given id and replaces it with the given category
deleteCategory(id: string) - deletes the category with the given id
createCategory(category: Category) - Creates the given category in the database

CCAHT-30 Create category server functions

---

components/HeaderAppBar/index.tsx

Resolves [CCAHT-51](https://team-16679321250140.atlassian.net/browse/CCAHT-51)
Before
After
[CCAHT-51]: https://team-16679321250140.atlassian.net/browse/CCAHT-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove duplicate Avatar Icon

---

pages/api/itemDefinitions/[itemDefinitionId].ts
pages/api/itemDefinitions/index.ts
server/models/ItemDefinition.ts

Added basic CRUD and fixed item definitions not having camel case in mongo collection

create api endpoints for item definition and fix item def collection name

---

pages/api/users/index.ts
server/actions/User.ts

Added the getUsers server function (that gets all the users), and the API endpoint. Made the API endpoint check for authorization as well :)

Ccaht 27 create get users server function and api endpoint

---

server/models/User.ts
utils/types/models.ts

Changed the 'imageURL' references to 'image'
Then tested by deleting user and creating a new one.

CCAHT-75-Rename-imageUrl-to-image

---

pages/api/attributes/[attributeId].ts
pages/api/categories/[categoryId].ts
pages/api/itemDefinitions/[itemDefinitionId].ts
pages/api/users/[userId].ts
server/actions/ItemDefinition.ts
server/actions/MongoDriver.ts

Implemented the aggregate queries in our mongo driver. to test, simply get the item definition with id `63edadfb566dfd57bfdb5456` from the API

CCHAT-64 mongo aggregate queries

---

components/InventoryItemListItem/index.tsx

Clicking on the kebab shows the menu and its options
Clicking off the menu or clicking one of the options closes the menu
Go to /tableTest to test it out!

CCAHT-68-Create-options-in-InventoryItemListItem-component-kebab-menu

---

components/AttributeForm/index.tsx
package-lock.json
package.json
pages/index.tsx

- Created `AttributeForm`, which accepts on `onSubmit` prop that will be called when the button is selected, and an `attribute` prop that allows an already created attribute to be passed in. This allows us to use the form for creating and updating an attribute.
To test:
First, put the default form on a page using this code:
```tsx
<AttributeForm submitBtnText="Add Attribute" onSubmit={(_e, formData) => console.log(formData)} />
```
Then, to test the edit functionality use the following code:
```tsx
const attribute: Attribute = {
name: "Size",
color: "#ff00ff",
possibleValues: ["Small", "Medium", "Large"]
}
<AttributeForm submitBtnText="Update Attribute" onSubmit={(_e, formData) => console.log(formData)} attribute={attribute} />
```
You should see the attribute you passed in populated in …

create attribute form component

---

utils/dbTestData.script

Generated test data had some misnamed field names. Script has already been ran

Fixed database setup script

---

components/AttributeAutocomplete/index.tsx
components/CheckInOutForm/QuantityForm.tsx
components/CheckInOutForm/index.tsx
package-lock.json
pages/checkIn.tsx
pages/checkOut.tsx
utils/attribute.ts
utils/hooks/usePrevious.ts
utils/types/models.ts
utils/types/requests.ts
utils/types/responses.ts

In this PR I have updated the `CheckInOutForm` component to accept an `inventoryItem` that will automatically fill out the fields in the form, and an `onChange` function that can be used to manage the state of the form from a parent component. I have left the test data in for ease of testing so after I get approved I will need to remove that and then get another approval.
You should test:
- playing with the form to ensure that everything works as it should
- passing an inventory item to the `CheckInOutForm` and ensuring that the data is filled out automagically

CCAHT-84 improve check in out form state

---

components/HistoryList/HistoryListItemKebab.tsx
pages/api/logs/index.ts

Added delete functionality to the history list item kebab menu

History List Item Kebab

---

components/CategoryList/CategoryListItem/index.tsx
components/CategoryList/CategoryListItemKebab/index.tsx
components/CategoryList/index.tsx
pages/settings/categories.tsx

Adds the table to the Settings/Category page with some of its basic features outlined in the JIRA story

CCAHT-114/CCAHT-115 Create-CategoryList-and-CategoryListItem-components

---

components/AttributeAutocomplete/index.tsx

CCAHT-165 hide menu when all attributes selected on check in/out

---

utils/dbTestData.script

Takeaway from the demo was she wants there to be a location attribute on every item definition. This PR adds a location attribute to every item definition and inventory item in the setup script

Added location attribute in setup script

---

components/HistoryList/HistoryListItemKebab.tsx
components/InventoryItemList/InventoryItemListItemKebab/index.tsx
components/UpsertItemForm/index.tsx
middleware.ts
pages/api/logs/export.ts
pages/checkIn.tsx
pages/checkOut.tsx
pages/items/new.tsx
pages/settings/attributes/[attributeId]/edit.tsx
pages/settings/attributes/create.tsx
pages/settings/index.tsx
pages/settings/items.tsx
test/api/attributes/[attributeId].test.ts
test/api/attributes/index.test.ts
test/api/categories/[categoryId].test.ts
test/api/categories/index.test.ts
test/api/inventoryItems/[inventoryItemId].test.ts
test/api/inventoryItems/checkIn.test.ts
test/api/inventoryItems/index.test.ts
test/api/itemDefinitions/[itemDefinitionId].test.ts
test/api/itemDefinitions/index.test.ts
test/api/logs/[logId].test.ts
test/api/logs/index.test.ts
test/api/notificationEmails/[notificationEmailId].test.ts
test/api/notificationEmails/index.test.ts
test/api/users/[userId].test.ts
test/api/users/index.test.ts
utils/constants/dialogRoutes.ts
utils/urls.ts

You tell me if you think this is helpful or overcomplicating things. I personally like to get away from hardcoding values whenever possible, even if the alternative is just as verbose. Main place to look is `utls/urls.ts`

Updated URL coding

---

components/CheckInOutForm/index.tsx
pages/checkIn.tsx
pages/checkOut.tsx

Optimize meaning use a `useMemo` hook so we don't parse a JSON string every re-render ;)

fix check in/out auto populate not working and optimize

---

components/HeaderAppBar/index.tsx

The only question I have is if it should be sticky on desktop view as well. I vote no, since the only added utility is from the signout button, and the pagination is about to be sticky.

CCAHT-103 Sticky app bar

---

pages/checkIn.tsx
pages/checkOut.tsx
pages/history.tsx

Just moved the form reset code to the success condition
Accidentally also completed CCAHT-172. Forgot to branch off before pushing.

CCAHT-227 Don't clear checkin/out form on failure

---

pages/settings/categories/[categoryId]/edit.tsx
pages/settings/categories/create.tsx
utils/types/forms.ts
utils/urls.ts

fixed url constant and used form data in create form

fix up category settings

---

server/actions/Logs.ts

History page search by staff name

---

components/AttributeAutocomplete/index.tsx
components/CheckInOutForm/index.tsx
components/HeaderAppBar/index.tsx
components/ItemDefinitionList/DesktopItemDefinitionList/DesktopItemDefinitionListItem/index.tsx
components/ItemDefinitionList/MobileItemDefinitionList/MobileItemDefinitionListItem/index.tsx
components/NavigationDrawer/index.tsx
components/UpsertItemForm/index.tsx
pages/history.tsx
pages/index.tsx
pages/inventory.tsx
utils/renderAttributeChips.tsx
utils/sortFns.ts

accidentally also did [CCAHT-272](https://team-16679321250140.atlassian.net/browse/CCAHT-272)
Covered:
- Dashboard page
- Category dropdown
- Checkin/out form
- staff
- category dropdown
- item definition dropdown
- assignee dropdown
- attributeautocomplete dropdown
- text field dropdowns
- number field dropdowns
- Inventory page
- category dropdown
- History page
- category dropdown
- Upsert item form
- category dropdown
- attribute dropdown
[CCAHT-272]: https://team-16679321250140.atlassian.net/browse/CCAHT-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ccaht 151 sort all autocompletes alphabetically
